import React from "react";
import Navbar from "../Navbar";
import Sidebar from "../Sidebar";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Valerio Cipolla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Navbar />
      {children}
    </div>
  );
};

export default Layout;
